version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '8000:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # express-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '5000:5000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  pg_data:
