version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  express-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pg_data:
